name: TS-Project
run-name: AWS sreate resources
on: [push]
jobs:
  Deploy_App:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is working"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: List file in repo
        run: ls ${{ github.workspace}}
      # Install the deps
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: Check if aws cli is installed
        run: |
          aws --version
      - uses: hashicorp/setup-terraform@v2
      - run: terraform version
