name: TS-Project Test
run-name: AWS create resources
on:
  workflow_run:
    workflows: ["TS-Project"]
    types:
      - completed

jobs:
  test_flask_app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is testing"
      - name: setup flask app
        run: |
          sudo mkdir -p /home/ubuntu/myproject
          sudo chmod 0755 /home/ubuntu/myproject
      - name: Download flask app
        run: |
          sudo curl -o /home/ubuntu/myproject/app.py -L "https://raw.githubusercontent.com/Aquilero/ts-wiederholung/main/myproject/app.py"
          sudo curl -o /home/ubuntu/myproject/requirements.txt -L "https://raw.githubusercontent.com/Aquilero/ts-wiederholung/main/myproject/requirements.txt"
          sudo chmod 0755 /home/ubuntu/myproject/app.py
          sudo chmod 0644 /home/ubuntu/myproject/requirements.txt
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Install the deps
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r /home/ubuntu/myproject/requirements.txt
      - name: Run tests
        run: |
          python -m unittest test_app.py
